#!/bin/bash
# Put this in your scripts directory, then run with
#
#    fix-filenames <directory>
#
# Example:
#
#    fix-filenames /cygdrive/t/88m6_spacey
#
# If you'd like to see what files will be renamed first, add "dryrun" to the
# command:
#
#    fix-filenames /cygdrive/t/88m6_spacey dryrun
#
DIR=$1
shift
DRYRUN=$1
if [[ "$DRYRUN" = "" ]]; then
    find "$DIR" -type f -print0 | xargs -0 -n 1 fix-filenames-single 0
else
    find "$DIR" -type f -print0 | xargs -0 -n 1 fix-filenames-single 1
fi
