#!/usr/bin/perl -w
use strict;

my $op;
my $was;
 
# Batch rename files with Perl regex substitutions
# Perl administration files rename
#
# Larry Wall's filename fixer: recipe 9.9 in Perl Cookbook 
 
$op = shift 
	or die "Usage: $0 expr [files]\n";
chomp(@ARGV = <STDIN>) unless @ARGV;
for (@ARGV) {
    $was = $_;
    eval $op;
    die $@ if $@;
    rename($was, $_) unless $was eq $_;
}
 
